### ISSUE TITLE
Adapter may be broken 

### ISSUE THREAD

**Issue by hoffmannd** [ioBroker/ioBroker.geofency#19]
The adapter crashes everytime I send a Webhook from Geofency 5.7

```
geofency.0 | 2018-10-18 12:16:46.820 | error | at process._tickCallback (internal/process/next_tick.js:104:9)
-- | -- | -- | --
geofency.0 | 2018-10-18 12:16:46.820 | error | at _combinedTickCallback (internal/process/next_tick.js:80:11)
geofency.0 | 2018-10-18 12:16:46.820 | error | at endReadableNT (_stream_readable.js:978:12)
geofency.0 | 2018-10-18 12:16:46.820 | error | at IncomingMessage.emit (events.js:185:7)
geofency.0 | 2018-10-18 12:16:46.820 | error | at emitNone (events.js:86:13)
geofency.0 | 2018-10-18 12:16:46.820 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.geofency/geofency.js:164:30)
geofency.0 | 2018-10-18 12:16:46.820 | error | at Object.parse (native)
geofency.0 | 2018-10-18 12:16:46.820 | error | SyntaxError: Unexpected token d in JSON at position 0
geofency.0 | 2018-10-18 12:16:46.819 | error | uncaught exception: Unexpected token d in JSON at position 0
```

I guess it may be because the webhook is now containing more information (the app release notes say there are SSID and BSSID contained from now on)?

**Comment by Apollon77** [comment]
please show the settings in the app ... you really selected JSON as format?
